### ISSUE TITLE
Can't build on Android

### ISSUE THREAD

**Issue by chrishaff** [championswimmer/nativescript-awesome-webview#1]
### Make sure to check the demo app(s) for sample usage 
Yes, tried building that - failed.

### Which platform(s) does your issue occur on?
I've only tried building on Android.

### Description
Sorry to be annoying, but I had the exact same issue with nativescript-advanced-webview and wrote it up there. https://github.com/bradmartin/nativescript-advanced-webview/issues/38

The error, using the demo for this project was a little different in that this project seems to want to use an earlier version of appcompat.  

Here is the (I think) relevant error from the console:
`C:\Users\Chris Haff\.gradle\caches\transforms-1\files-1.1\appcompat-v7-26.1.0.aar\056d9800ef08bb71e4f5d3d356616abb\res\values-v26\values-v26.xml:9:5-12:13: AAPT: error: resource android:attr/colorError not found.

C:\Users\Chris Haff\.gradle\caches\transforms-1\files-1.1\appcompat-v7-26.1.0.aar\056d9800ef08bb71e4f5d3d356616abb\res\values-v26\values-v26.xml:13:5-16:13: AAPT: error: resource android:attr/colorError not found.

C:\Users\Chris Haff\.gradle\caches\transforms-1\files-1.1\appcompat-v7-26.1.0.aar\056d9800ef08bb71e4f5d3d356616abb\res\values-v26\values-v26.xml:17:5-93: AAPT: error: style attribute 'android:attr/keyboardNavigationCluster' not found.
`

**Comment by championswimmer** [comment]
Pretty strange as the demo builds on mine. 
Will check again on a fresh setup

**Comment by chrishaff** [comment]
Thanks for checking.  I have tried Android SDK Build-tools 27.0.1 and 27.0.2. All components/libs should be up to date.
nativescript 4.1.2
tns-core-modules 4.1.1
tns-android 4.1.3

**Comment by championswimmer** [comment]
try changing this to 27.1.1
https://github.com/championswimmer/nativescript-awesome-webview/blob/master/src/platforms/android/include.gradle#L10

**Comment by chrishaff** [comment]
It's now a couple of version later for {n} and this is compiling fine now.  
I'm not sure it's applicable here, but with issues like this it seems useful to 
`tns platform remove android`
`tns platform add android`
to get gradle to clean up it's stuff.

Thanks @championswimmer !
